spring:
  application:
    name: survey
  datasource:
    url: jdbc:h2:file:./db/survey-db;AUTO_SERVER=TRUE;
    username: sa
    password:
  jackson:
    mapper[DEFAULT_VIEW_INCLUSION]: true
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: ${PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /survey

logging:
  level[net.talaatharb]: DEBUG
  level[org.springframework.web]: DEBUG

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.0}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  api-docs:
    path: '/v3/api-docs'
  swagger-ui:
    url: '/v3/api-docs'